### ISSUE TITLE
Keyboard support? 

### ISSUE THREAD

**Issue by werdnus** [reHackable/awesome-reMarkable#10]
Anyone know if someone's working on keyboard support through the microUSB port (and, I suppose, a simple text editor app)?

**Comment by CTXz** [comment]
I'm sorry but this isn't really an issue nor an discussion directly related to our list.

Perhaps the community [reMarkable sub-reddit](https://www.reddit.com/r/RemarkableTablet/) or the community [reMarkable discord channel](https://discord.gg/vcFqGek) is a more appropriate place to ask.

**Comment by sandsmark** [comment]
I use https://github.com/reMarkable/fingerterm and vim with a usb keyboard (and a normal micro-usb adapter).

**Comment by maxmcd** [comment]
@sandsmark would you mind providing more information about this setup? Does the keyboard work system-wide?

**Comment by heavyimage** [comment]
@sandsmark I second @maxmcd's question!  Very interested in this.

**Comment by bmuyl** [comment]
Same here

**Comment by oscarmorrison** [comment]
+1 Whats your setup @sandsmark ? Please share
