### ISSUE TITLE
[Suggestion] Add warning about Factory Reset and root password

### ISSUE THREAD

**Issue by plan5** [reHackable/awesome-reMarkable#106]
I suggest to add another warning that a Factory Reset will only delete /home/root/* and especially that it will generate a new root password.

For example:
Factory resetting through xochitl will generate a new root password and it will only delete the files in /home/root/. Be careful not to brick your device by removing alternative launchers this way.

Background: I've made the unpleasant experience of bricking my rM2 by running a factory reset. I thought it would be like an update, bringing the whole filesystem back to the original state. 

However, rm2fb service remained enabled but the binary was deleted as it resided in /home/root/. This way, the GUI cannot boot and the password is inaccessible without the necessary hardware to access the OTG mode.

I read the warnings beforehand and this would have avoided a lot of trouble for me.

**Comment by fenollp** [comment]
Maybe care should be taken in out 3rd party softwares to fail safe in the case of a deleted /home/root as well ;)

Sorry for your loss!

**Comment by Ameb** [comment]
I added a disclaimer so we can close this
