### ISSUE TITLE
old os

### ISSUE THREAD

**Issue by dgrin1** [reHackable/awesome-reMarkable#107]
Hello friends - I inadvertently overwrote the Remarkable Desktop app on my Mac with a version that does not run with the current OS> I'd like to go back to an odler version, but don't see any of htese archived on the remarkable website. Does anyone know where I can find old versions of the official OS?

Thanks

**Comment by gveres** [comment]
Hi, I have an older installer of desktop app, give it a try - https://www.dropbox.com/s/1ff4g042mqn9sut/reMarkable-1.7.1.dmg

**Comment by dgrin1** [comment]
Thank you! that worked!

**Comment by Ameb** [comment]
Glad you got it solved!
Those kind of questions are probably more suited to the community chats / forums / reddit. There are links on the [remarkablewiki](https://remarkablewiki.com/)
