### ISSUE TITLE
Question: collaborate by syncing two remarkable screens

### ISSUE THREAD

**Issue by mahrud** [reHackable/awesome-reMarkable#110]
Sorry if this isn't the right place for this, but I was wondering if anyone is working on syncing two (or more) remarkable screens across a network. The idea is to write on one remarkable and see the result on the other remarkable live, and vice versa.

As a weaker alternative, is it possible to write on a remarkable by writing on a laptop screen? e.g., draw a line on the laptop and see the result on a connected remarkable live. Using projects like @evidlo's [remarkable_mouse](https://github.com/evidlo/remarkable_mouse) it is possible to write on a laptop using remarkable, but I'm looking for the inverse to this. Eventually the goal would be to connect to tools like https://excalidraw.com so multiple people can collaborate on remarkables, laptops, tablets, etc.

This would be like collaborating using a whiteboard, but remotely with each person having a remarkable.

**Comment by burdges** [comment]
#105 maybe?

**Comment by fenollp** [comment]
You should be able to start off of #111

**Comment by mahrud** [comment]
> You should be able to start off of #111

This seems like exactly what I had in mind! What stage is the whiteboard feature in? Do you have a demo anywhere? Does it also support collaborating across a remarkable and a laptop?

**Comment by fenollp** [comment]
Server is here https://github.com/fenollp/reMarkable-tools/blob/v0.3.2/whiteboard-server/main.go
Client is here https://github.com/fenollp/reMarkable-tools/blob/v0.3.2/marauder/src/bin/whiteboard.rs
Communication uses gRPC (with protobuf v3).
It is under somewhat active development but the base room-based live communication is already here. My work is now more about in-app UI-making tools and AI.
There are some IRL screenshots on that reddit page but no video (for now).
If you have rm2 you can get the framebuffer shim along with the latest release https://github.com/fenollp/reMarkable-tools/releases/tag/v0.3.2 and try it out yourself, although I haven't encountered anyone on the default server in a while.
I have an issue open for laptop (browser) communication (and this encompasses even just spectate mode) but haven't committed much in this direction.

If you have any request feel free to open an issue there. I'd be happy to collaborate on this :)

**Comment by mahrud** [comment]
Thank you! I actually don't have a remarkable currently, but this feature is worth getting one.
