### ISSUE TITLE
Dark mode for reading and writing

### ISSUE THREAD

**Issue by Emnlv** [reHackable/awesome-reMarkable#125]
Hello,

Do you know if there is any possibility to use a dark mode for reading and writing  [white words on a black surface] for rM and rM2? 

Thank you in advance

**Comment by beardhatcode** [comment]
You could make a template that is just black and write on it with a white pen

**Comment by Ameb** [comment]
For pdfs you could postprocess them to modify font color and background with `k2pdfopt` for example. For epubs, look for software to transform them to pdfs.

This question would be more suited for the communities (discord, facebook, reddit).

I'm closing the issue as it is not related to the repo, but feel free to comment if needed.
