### ISSUE TITLE
mdview

### ISSUE THREAD

**Issue by c-smile** [reHackable/awesome-reMarkable#135]
[MDView](https://quark.sciter.com/quark-application-samples/hello-markdown/) is a desktop viewer application for Windows, Mac and Linux. The [MDView source](https://github.com/c-smile/sciter-js-sdk/tree/main/samples.sciter/applications.quark/mdview) is a part of Sciter SDK.

**Comment by matomatical** [comment]
MDView uses [remarkableJS](https://github.com/jonschlinkert/remarkable), a javascript "Markdown parser, done right", but appears to have nothing to do with the [reMarkable e-ink tablet](https://www.remarkable.com/). The latter is the subject of this repository.

**Comment by Ameb** [comment]
As matomatical has said, `MDView` is unrelated. I will close this issue.
