### ISSUE TITLE
Add rm2-screen to list

### ISSUE THREAD

**Issue by m6c7l** [reHackable/awesome-reMarkable#153]
Candidate for Screen Sharing/Streaming:
https://github.com/m6c7l/rm2-screen

**Comment by StachuDotNet** [comment]
While I'm not associated with the repo/maintainer, I'm fairly certain a PR
adding this tool to the list would be accepted!

**Comment by Eeems** [comment]
https://github.com/reHackable/awesome-reMarkable/blob/master/CONTRIBUTING.md

If you want to add something to the list, please open a PR to add it.
