### ISSUE TITLE
Any way to adjust pressure sensitivity?

### ISSUE THREAD

**Issue by rgaufman** [reHackable/awesome-reMarkable#176]
Does anyone know any way to adjust the pressure sensitivity? - I find that I need to press far too hard for the ballpoint pen, I would like to increase the sensitivity.

**Comment by Eeems** [comment]
This issues list is not a general discussion forum for finding things. It's for suggesting changes to how the list works. To get community support, you can go to one of the following discussion forums:

- [Discord](https://discord.gg/ATqQGfu)
- [Matrix](https://matrix.to/#/#remarkable:matrix.org)
- [Reddit](https://reddit.com/r/remarkableTablet)

If you need official support, you can get it directly from reMarkable: https://support.remarkable.com
