### ISSUE TITLE
It'd help if the list indicated which levels of reMarkable could support which packages

### ISSUE THREAD

**Issue by jkesselm** [reHackable/awesome-reMarkable#198]
My tablet is currently running 3.9.3.1986, and unfortunately many (most? all?) of the available packages support only 2.x versions of ReMarkable. It'd help tremendously to know what my options were at a glance, rather than having to chase into each project's docs. In particular I don't know of a launcher that is compatible with v3, and toltec officially doesn't go past v2 yet.

I'd even be willing to consider rolling the tablet back to v2 of the reMarkable package if necessary -- if there's a documented process for that and if there's a way to make sure it can't accidentally be updated into failing even if someone "helpfully" flips the Automatic Update switch.

**Comment by Eeems** [comment]
This appears to largely duplicate #177

> I'd even be willing to consider rolling the tablet back to v2 of the reMarkable package if necessary -- if there's a documented process for that and if there's a way to make sure it can't accidentally be updated into failing even if someone "helpfully" flips the Automatic Update switch.

https://remarkable.guide/faqs.html#can-i-downgrade-to-a-different-os-version
