### ISSUE TITLE
Not an issue but a project you may /or not be interested in

### ISSUE THREAD

**Issue by xvdp** [reHackable/awesome-reMarkable#199]
I didnt see this depot until I looked into reading .rm files,

When remarkable software version hit 3.5 they removed the ability to upload files with the ip interface, instead requiring an app which pissed me off so i instead upladed thru ssh and modified content and metadata files, and ensured no automatic updates. Since that goes against my use of the tablet - all i care is to upload  pdfs, fast. and i dont need any new user accounts - 

I had to make it simpler for my kid yesterday   so I built a mini project with console scripts - tested on ubuntu but i have to set it up for a mac as well
* `pdf_to_remarkable filename.pdf "visible name parent"`
* `backup_remarkable local_folder`
* `remrkable_file_graph local_backup_folder`
If anyone is interested
https://github.com/xvdp/unremarkable

**Comment by Eeems** [comment]
I've been informed that uploading using the usb web interface is still working in 3.8. Are you sure it's been removed in 3.5? Or have you just not turned it on?

**Comment by Eeems** [comment]
If you'd like to add the repository to the list, please check out [CONTRIBUTING.md](https://github.com/reHackable/awesome-reMarkable/blob/master/CONTRIBUTING.md) for instructions how to.
