### ISSUE TITLE
Entware package manager

### ISSUE THREAD

**Issue by Evidlo** [reHackable/awesome-reMarkable#20]
I'd like to propose adding [remarkable_entware](https://github.com/Evidlo/remarkable_entware), which is a modified install script for the [Entware](http://github.com/entware/entware) software repository.

**Comment by StachuDotNet** [comment]
@Evidlo This looks really cool, but I'm too stupid to fully understand what this is. (different background - never done "embedded" stuff before). Can you please list some idea use cases for this?

**Comment by Evidlo** [comment]
It's a package manager.  It lets you install various programs and utilities, like vim, htop, python, etc.

**Comment by CTXz** [comment]
Leave a pull request and we will gladly accept the project. Thanks for the suggestion.

**Comment by Ameb** [comment]
#21 merged 😀
