### ISSUE TITLE
reMarkable Web App is no longer working

### ISSUE THREAD

**Issue by michaelmior** [reHackable/awesome-reMarkable#28]

**Comment by StachuDotNet** [comment]
@michaelmior I think you're confused.

This repository is unaffiliated with the reMarkable team.
This repository simply collects links to unofficial software to be used on, or in conjunction with, the rM.

If you're having issues with the official software, you should close this issue and post your question through the official support channels: https://support.remarkable.com/hc/en-us/requests/new?ticket_form_id=360000022578

**Comment by michaelmior** [comment]
I understand that. I should have clarified that I'm referring to the "reMarkable Web App" link in the "Cloud Tools" category.

**Comment by CTXz** [comment]
Thank you for the notice! I'll be taking down the project from the list since I have failed to find any other traces of it.
