### ISSUE TITLE
Suggestion for incrementally improving the topics

### ISSUE THREAD

**Issue by grantwparks** [reHackable/awesome-reMarkable#36]
Thank you; this is a great source of information and it will motivate people to create more tools.
One suggestion I'd make is that a wrapper for a specific language that calls reMarkable API would most accurately be called an "SDK", at least from a developer's perspective.  An API would be if someone offered another cloud service that then talked to reMarkable's.

**Comment by Ameb** [comment]
You are right. This is related to #24, which i have been thinking about it for weeks but hadn't come to an actual good way to organize the resources here.
