### ISSUE TITLE
SSH password gone after factory reset on ReMarkable

### ISSUE THREAD

**Issue by kchappe** [reHackable/awesome-reMarkable#38]
Factory reset left me with no SSH password. It says
username 'root' and the password ''.  

Leaving password blank doesn't work in WinSCP

Help!

**Comment by CTXz** [comment]
This issue is absolutely unrelated to this repo. Please ask for help at a more appropriate place! Perhaps start out with the [reMarkable tablet subreddit](https://www.reddit.com/r/RemarkableTablet/) or the [reMarkable discord channlel](https://discord.gg/JSSGnFY).
