### ISSUE TITLE
upside down version of UI

### ISSUE THREAD

**Issue by bmuyl** [reHackable/awesome-reMarkable#40]
Would any one be able to produce an upside down version of the UI ? 
so we can work / draw / write with the buttons above the screen rather than under the screen right below the hand, where you don't want them ?

**Comment by bmuyl** [comment]
would also make it easier to work with the device pluged

**Comment by edupont** [comment]
Flipping the user interface is easy, but translating the mouse events is something I didn't manage to do.

**Comment by bmuyl** [comment]
could remarkable team be helpfull on such a matter ? 
I mean some of their code is open source

**Comment by sandsmark** [comment]
The only way to do it (without binary patching the application) that I can think of is to patch the drivers (mxc_epdc, cyttsp and wacom_i2c), and deploy a custom kernel flipping all coordinates. So not very straightforward unfortunately.

**Comment by CTXz** [comment]
I'm afraid this issue isn't directly related to the awesome list. I highly recommend using other places to discuss the implementation of new features, such as the [reMarkable community subreddit](https://www.reddit.com/r/RemarkableTablet/) or the [reMarkable community discord](https://discord.gg/JSSGnFY) .
