### ISSUE TITLE
Zen mode with right button to switch from pen to eraser

### ISSUE THREAD

**Issue by ZacharieALES** [reHackable/awesome-reMarkable#54]
Hello,

Could it be possible for left-handed player to switch from the pen to the eraser with the right button in zen mode? (since it is my free hand when I write)

Otherwise, this mode is so great! I use it all the time. 
The new button to easily switch from 1 recent document to another also is very useful. Now when I read an article, I can put its notations in a notebook.

Thanks!

PS: Have you considered assigning an action to the third button in zen mode? For me it could be nice to open the "recent file" window you created. Another suggestion would be the undo button (but it would not be as useful as I can erase easily in zen mode).

**Comment by Ameb** [comment]
Your request should be targeted at [ddvk/remarkable-hacks](https://github.com/ddvk/remarkable-hacks). The right button suggestion has already been requested https://github.com/ddvk/remarkable-hacks/issues/12

Closing the issue here as it is unrelated to the awesome list.

**Comment by ZacharieALES** [comment]
Oh indeed, sorry
