### ISSUE TITLE
remt

### ISSUE THREAD

**Issue by Ameb** [reHackable/awesome-reMarkable#6]
We might add this [python library](https://pypi.org/project/remt) to the list, it is hosted on [gitlab](https://gitlab.com/wrobell/remt).

> Features
> ========
> `remt` project features are
> 
> - reMarkable tablet operations
> 
>   - list files and directories
>   - create directories
>   - export a notebook as PDF file
>   - export an annotated PDF document
>   - import a PDF document
> 
> - significantly smaller PDF files comparing to the ones exported by the
>   reMarkable tablet
> - export supports
> 
>   - multi-page notebooks and PDF files
>   - the following drawing tools
> 
>       - ballpoint (no brush supported yet)
>       - fineliner
>       - sharp pencil with pencil brush
>       - highlighter
>       - eraser
> 
> - `remt` project can be used as a library for UI applications

**Comment by mseri** [comment]
Looks quite good! Why does it matter if it is on gitlab?

**Comment by Ameb** [comment]
It doesn't really matter, not for me at least. Sorry for the wording there

**Comment by mseri** [comment]
I have been using `remt` for a while now, it works really well!

**Comment by CTXz** [comment]
Thanks for the feedback. `remt` has been added with commit aec78125bc1b2128f61d11224192a98dde3d791f.
