### ISSUE TITLE
Question: Is there a project to be able to use Pocket on reMarkable?

### ISSUE THREAD

**Issue by Alexis-benoist** [reHackable/awesome-reMarkable#60]
Thanks for any input :)

**Comment by Ameb** [comment]
https://github.com/GliderGeek/pocket2rm

https://old.reddit.com/r/RemarkableTablet/comments/g3spbz/pocket_articles_to_the_remarkable_tablet/

Also check http://www.harecoffee.com/rm.html

**Comment by Alexis-benoist** [comment]
I didn't saw it :)

Thanks !
