### ISSUE TITLE
Three links

### ISSUE THREAD

**Issue by TechnologyClassroom** [reHackable/awesome-reMarkable#62]
I have three links that could go on your awesome list.

* [Adding a microSD card](http://www.davisr.me/projects/remarkable-microsd/)
* [reMarkable's github](https://github.com/reMarkable)
* [reMarkable's sources](https://remarkable.engineering/deploy/)

**Comment by Ameb** [comment]
I think we can add the github link in a disclaimer about the list being unrelated to reMarkable AS etc.

**Comment by gaffling** [comment]
What about such Links like https://www.einkpads.com/
