### ISSUE TITLE
[Cloud Tools] reMarkable-explorer.com

### ISSUE THREAD

**Issue by MikaGr** [reHackable/awesome-reMarkable#87]
Hi,
Maybe you can add it to your list.
It's a cloud based app that allow you to manage your files and folders, download/upload files, etc.
Link : https://remarkable-explorer.com
Regards,
Mikael

**Comment by LinusCDE** [comment]
Hi. I think you should just go ahead and make a PR out of it.

I personally somewhat dislike the idea of adding non-FOSS solutions here, seeing that [RemaDroid/reMarkable Uploader](https://github.com/reHackable/awesome-reMarkable/pull/73) <sup>[1](https://www.reddit.com/r/RemarkableTablet/comments/kcfht6/remarkable_uploader_android_app/)</sup> got added, and no rule in CONTRIBUTING.MD forbidding that, I don't see any argument against adding this one.

The only critera other than the rules from the contributing doc that relates is [this](https://github.com/sindresorhus/awesome/blob/main/awesome.md#only-awesome-is-awesome):
> ## Only awesome is awesome
> 
> Research if the stuff you're including is actually awesome. Only put stuff on the list that you or another contributor can personally recommend. You should rather leave stuff out than include too much.

(While I dislike the idea of non-FOSS solutions, they have their own perks for the developer and in turn for the users. Doing a lot on GitHub and the likes made me most likely biased in that matter.)

**Comment by Barabazs** [comment]
This should be closed. The app has been taken down.
More info here: #95
