### ISSUE TITLE
Add 'remouseable' to [Other] 

### ISSUE THREAD

**Issue by jebediah2** [reHackable/awesome-reMarkable#89]
Having verified [remouseable](https://github.com/kevinconway/remouseable) works on the reMarkable 2 and is so easy to use, both wired and wirelessly, I thought you could add it to the 'Other' list.

The only thing you need to know for RM2 is that you will have to add this option in the command line call:
`--event-file /dev/input/event1`
So the whole command should look like this:
`remouseable --event-file /dev/input/event1 --ssh-ip="192.168.1.XXX:22" --ssh-password="yourpassword"`

The binary is in the [release section](https://github.com/kevinconway/remouseable/releases), you then rename it to `remouseable`, and make it executable with `chmod +x` before going ahead with the command line call.

**Comment by LinusCDE** [comment]
I think, it's not that important how easy a mod is to set up or whether it works with the rM 1 and/or rM 2 (for now at least).

Just go ahead and create a PR to add the entry yourself. The few rules for entries are [here](https://github.com/reHackable/awesome-reMarkable/blob/master/CONTRIBUTING.md). If you want to, I can also create the PR.
